security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email # Symfony utilisera getEmail() qui mappe sur la colonne 'login'

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                default_target_path: app_commande
            logout:
                path: admin_logout
                target: admin_login

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_GESTIONNAIRE }